#pragma once

// From glafw.h
#define EVIL_MOUSE_BUTTON_1         0
#define EVIL_MOUSE_BUTTON_2         1
#define EVIL_MOUSE_BUTTON_3         2
#define EVIL_MOUSE_BUTTON_4         3
#define EVIL_MOUSE_BUTTON_5         4
#define EVIL_MOUSE_BUTTON_6         5
#define EVIL_MOUSE_BUTTON_7         6
#define EVIL_MOUSE_BUTTON_8         7
#define EVIL_MOUSE_BUTTON_LAST      EVIL_MOUSE_BUTTON_8
#define EVIL_MOUSE_BUTTON_LEFT      EVIL_MOUSE_BUTTON_1
#define EVIL_MOUSE_BUTTON_RIGHT     EVIL_MOUSE_BUTTON_2
#define EVIL_MOUSE_BUTTON_MIDDLE    EVIL_MOUSE_BUTTON_3